### ISSUE TITLE
Is this sample still supposed to be working?

### ISSUE THREAD

**Issue by stevebeauge** [mmsharepoint/ReactOutlook2SP_SPFx#9]
Hello,

I'm trying to compile and deploy this sample as is, without any modification.

When trying to add the addin to outlook (new outlook desktop), I got:

![image](https://github.com/mmsharepoint/ReactOutlook2SP_SPFx/assets/184604/194e9b29-b1c1-416b-b1a7-74e6a867f7b8)

In the dev tool, I can see `Refused to display 'https://login.microsoftonline.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`.

What I believe, is that the office addin is simply no more usable.

Do you have any insight?

**Comment by mmsharepoint** [comment]
In fact SPFx add-addins for outlook (and office) never came out of beta and were a deathbirth unfortunately. 
With Teams Messaging Extensions you are meanwhile at least able to post something in a new mail (compose box) but not do something in the context of an existing retrieved mail in a folder…

**Comment by stevebeauge** [comment]
Thanks for your feedback.

I came to the same conclusion but didn't find any  official statement.

Quite disappointed by M$.
